name: Deploy to Surge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          # Мы добавим рандомное число к домену, чтобы 100% не было повторов
          # Проверь, чтобы секреты назывались SURGE_LOGIN и SURGE_TOKEN
          npx surge . evacasino-${{ github.run_number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }} --login ${{ secrets.SURGE_LOGIN }}
